apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller-${NAMESPACE}
  namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller-${NAMESPACE}
  namespace: ${NAMESPACE}
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller-${NAMESPACE}
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tiller-${NAMESPACE}
subjects:
  - kind: ServiceAccount
    name: tiller-${NAMESPACE}
