apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller-${NAMESPACE}
  namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller-${NAMESPACE}
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-operator
subjects:
  - kind: ServiceAccount
    name: tiller-${NAMESPACE}
