apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
  - nonResourceURLs: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tiller
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
