---
# Source: flux/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-dev
  namespace: dev
  labels:
    app: flux
    chart: flux-0.9.2
    release: flux-dev
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux
      release: flux-dev
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "true"
      labels:
        app: flux
        release: flux-dev
    spec:
      serviceAccountName: flux-dev
      volumes:
      - name: kubedir
        configMap:
          name: flux-dev-kube-config
      - name: git-key
        secret:
          secretName: flux-dev-git-deploy
          defaultMode: 0400
      - name: git-keygen
        emptyDir:
          medium: Memory
      containers:
        - name: flux
          image: "docker.io/weaveworks/flux:1.12.1"
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 3030
            protocol: TCP
          volumeMounts:
          - name: kubedir
            mountPath: /root/.kubectl
          - name: git-key
            mountPath: /etc/fluxd/ssh
            readOnly: true
          - name: git-keygen
            mountPath: /var/fluxd/keygen
          env:
          - name: KUBECONFIG
            value: /root/.kubectl/config
          args:
          - --ssh-keygen-dir=/var/fluxd/keygen
          - --k8s-secret-name=flux-dev-git-deploy
          - --memcached-hostname=flux-dev-memcached
          - --memcached-service=
          - --git-url=git@github.com:skleinjung/thrashplay-deployment
          - --git-branch=master
          - --git-path=deployments/environments/dev
          - --git-user=Weave Flux
          - --git-email=support@weave.works
          - --git-set-author=false
          - --git-poll-interval=1m
          - --git-timeout=20s
          - --sync-interval=1m
          - --git-ci-skip=false
          - --registry-poll-interval=1m
          - --registry-rps=200
          - --registry-burst=125
          - --registry-trace=false
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            
