---
# Source: flux/templates/helm-tls.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-dev-helm-tls-ca-config
  namespace: dev
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFlzCCA3+gAwIBAgIULDct9IZsM5FU6E+zL6pFG9o5/RQwDQYJKoZIhvcNAQEL
    BQAwWzELMAkGA1UEBhMCVVMxEjAQBgNVBAgMCU1pbm5lc290YTEOMAwGA1UEBwwF
    RWFnYW4xEzARBgNVBAoMClRocmFzaHBsYXkxEzARBgNVBAMMCnRpbGxlci1kZXYw
    HhcNMTkwNTAyMTU1NTUwWhcNMzkwNDI3MTU1NTUwWjBbMQswCQYDVQQGEwJVUzES
    MBAGA1UECAwJTWlubmVzb3RhMQ4wDAYDVQQHDAVFYWdhbjETMBEGA1UECgwKVGhy
    YXNocGxheTETMBEGA1UEAwwKdGlsbGVyLWRldjCCAiIwDQYJKoZIhvcNAQEBBQAD
    ggIPADCCAgoCggIBAO2D3Tg2+BSBwKwkBoaA5UvtOBNQYyw7w9qWDK+KF/A7wSBK
    t8u3cDFDKfKHHv9zTmzwjohGKghVas9ssY5Nq5pwUyUGTsmlsYUaxmzfX9mqsq5i
    CG8P2h/Z0uNgseVFrPE5MuunhFShzbstGejtGOUWb/U96rC6/5BQmJj/kFfpsFHy
    +unyhg8wfZ0go8FwBya+FJkG5Pfhm2pRaP5bq3ldIzn/NNI4lxeGEQaSwtWy5JEk
    UnW/bm8o2ivMRsbh0crxj1GQLUIrexGFW1uVeHj0zhSaYuPHZuklP67fouD7pg8K
    Scyhqn63+LFrkx72GzQEJVNDHcwGsoNQUIZ5DDLh4gO/4KCU63FOxBFRf7GE0qwK
    j1DR3gGzqy4oMz47c5sz6qlxvykhfcC+q9AAbENJJPNZJQVIEOd5Kr4Bhgxv1Xko
    EX3pcen4VGJuyySMhj6SrahD6QNwp78cGWt6FchBsubYckz2hTnSPtoeMrksaOMD
    /C5h16affeLwBQEzwJddkRX8O0XUS1ycQQ9EiUBvECy3D40w6ftrOdGH9yJK9WFc
    XQ4wTU7bwUWMt+kmC//RL9QSAnbOA4C5udDmaDulqlKijzdmob2efzLGQUkDcy7a
    sTRa+c9qzELQ8LSiG3tDyMdYBS5rObOW5eLkRPsy8fEM6KUUBpozigiYY+fJAgMB
    AAGjUzBRMB0GA1UdDgQWBBTTkN86/X8D8v29HY0Z7cWvg6BJLDAfBgNVHSMEGDAW
    gBTTkN86/X8D8v29HY0Z7cWvg6BJLDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3
    DQEBCwUAA4ICAQDdq1rFeBxJ9mOo0nnftS0SV+XTN3IDXRtGujtajRUAaWjZUtPa
    AJ5coz/zKJlY5pwfE9ygMMN6xFk5my6wuCYPT5oAcXJTvEI4MUszgt6ZBHGNPecF
    5Kxm9TaL92BYC7RNk9wafyq/pK3vqJzQvLt4CbKplRD1rWAbfViNwT4Bf804kjRP
    X8pqIKfaXzs9kQ5zgivh0OoXSgxAZF4wypTqaCYWdxUVzHsyQgJSZJ1mV9Ix8/V8
    qZjQeygQ0Hh6ChXdojtbBdN2B8qnBdKdezxFbGoaA7ZuDLkg624Gt/ZpLMVmL4fL
    hVgnV25PL9X7Sgwa2g3AmEHgwXx5RX/sxtx5fRNELrzwS6BY7h8RmxJ0gVtyo6g8
    fmyGFKydQL/bzG+SNClSmbxlC2w/COtVPltDhCGG60t2OoVMuUG0FoOWisTLLpGZ
    slAHff/j+etLS+g+WuKQeE0ieADApgCXzvn8SesAwNw8VzqZfzwE9JgGLHepVgWP
    Bf+n3pDWE7C225IbLxgSQuWJX44Mq3oKWbIfuU4S8sqtz3YkpaVSuyUOKa52GO12
    eQGp3TzDIo3dOAeiKQ3h1FgckPmSzl32e3d4KT6KeOMsygk8M+/AQ8B6HG73q8Eq
    UvSPRCYWqrYZ5E5KElXb+JQSRUptLOIc4SiXPs+A+uFbWs/29x8f39L80Q==
    -----END CERTIFICATE-----