---
# Source: flux/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flux-dev
  namespace: dev
  labels:
    app: flux
    chart: flux-0.9.2
    release: flux-dev
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 3030
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: flux
    release: flux-dev
