apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller-dev
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller-dev
  namespace: dev
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller-dev
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tiller-dev
subjects:
  - kind: ServiceAccount
    name: tiller-dev
