apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    app: grafana
    name: grafana-config
  namespace: monitoring
data:
  prometheus-data-source.yml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-service:30000
      isDefault: true
      version: 1
      editable: false

  dashboards-provider.yml: |-
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 3600 #how often Grafana will scan for changed dashboards
      options:
        path: /etc/grafana/provisioned-dashboards