---
# Source: flux/templates/helm-operator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-helm-operator
  namespace: flux
  labels:
    app: flux-helm-operator
    release: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux-helm-operator
      release: flux
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "true"
      labels:
        app: flux-helm-operator
        release: flux
    spec:
      serviceAccountName: flux
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
          defaultMode: 0400
      - name: helm-tls-certs
        secret:
          secretName: helm-client-certs
          defaultMode: 0400
      - name: helm-tls-ca
        configMap:
          name: flux-helm-tls-ca-config
          defaultMode: 0600
      containers:
      - name: flux-helm-operator
        image: "docker.io/weaveworks/helm-operator:0.8.0"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3030
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
          readOnly: true
        - name: helm-tls-certs
          mountPath: /etc/fluxd/helm
          readOnly: true
        - name: helm-tls-ca
          mountPath: /etc/fluxd/helm-ca
          readOnly: true
        args:
        - --git-timeout=20s
        - --git-poll-interval=3m
        - --charts-sync-interval=3m
        - --update-chart-deps=true
        - --log-release-diffs=false
        - --tiller-namespace=kube-system
        - --tiller-tls-enable=true
        - --tiller-tls-key-path=/etc/fluxd/helm/tls.key
        - --tiller-tls-cert-path=/etc/fluxd/helm/tls.crt
        - --tiller-tls-verify=true
        - --tiller-tls-ca-cert-path=/etc/fluxd/helm-ca/ca.crt
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          