---
# Source: flux/templates/memcached.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-memcached
  namespace: flux
  labels:
    app: flux-memcached
    release: flux
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flux-memcached
      release: flux
  template:
    metadata:
      labels:
        app: flux-memcached
        release: flux
    spec:
      containers:
      - name: memcached
        image: memcached:1.4.25
        imagePullPolicy: IfNotPresent
        args:
        - -m 512    # Maximum memory to use, in megabytes. 64MB is default.
        - -p 11211    # Default port, but being explicit is nice.
        - -I 5m #  Maximum size for one item
        ports:
        - name: memcached
          containerPort: 11211
        resources:
          {}
          
---
apiVersion: v1
kind: Service
metadata:
  name: flux-memcached
  namespace: flux
  labels:
    app: flux-memcached
    chart: flux-0.9.1
    release: flux
    heritage: Tiller
spec:
  ports:
    - port: 11211
      targetPort: memcached
      protocol: TCP
      name: memcached
  selector:
    app: flux-memcached
    release: flux
