apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: monitoring
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.1
spec:
  releaseName: kube-state-metrics
  chart:
    git: git@github.com:helm/charts
    repository: https://github.com/helm/charts/tree/master/stable/kube-state-metrics
    name: stable/kube-state-metrics
    version: 1.1.0
