apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: flux
  name: ${NAMESPACE}-release-operator
  namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: flux-${NAMESPACE}-release-operator
  namespace: ${NAMESPACE}
  labels:
    app: flux
    chart: flux-0.9.2
    release: flux-${NAMESPACE}
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-operator
subjects:
  - name: ${NAMESPACE}-release-operator
    kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: flux-${NAMESPACE}-namespace-viewer
  labels:
    app: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-viewer
subjects:
  - name: ${NAMESPACE}-release-operator
    kind: ServiceAccount
