apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: flux
  name: flux-${NAMESPACE}
  namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: flux-${NAMESPACE}
  namespace: ${NAMESPACE}
  labels:
    app: flux
    chart: flux-0.9.2
    release: flux-${NAMESPACE}
    heritage: Tiller
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: flux-${NAMESPACE}
  namespace: ${NAMESPACE}
  labels:
    app: flux
    chart: flux-0.9.2
    release: flux-${NAMESPACE}
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-${NAMESPACE}
subjects:
  - name: flux-${NAMESPACE}
    kind: ServiceAccount